# Generated by Django 4.2.2 on 2023-07-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abiscemenu", "0002_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="breve_description",
            field=models.CharField(max_length=90),
        ),
    ]
