# Generated by Django 4.2.2 on 2023-07-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abiscemenu", "0003_alter_event_breve_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="events_pic"),
        ),
    ]
